### ISSUE TITLE
\11-remote-virtual-desktops\ Spice \ Ubuntu-18.04-gnome - Spice mirroring problems

### ISSUE THREAD

**Issue by yanbx** [fadams/docker-gui#2]
Hello, again, I'm trying \11-remote-virtual-desktops\ Spice \ Ubuntu-18.04-gnome-Spice
The basic image pull FROM ubuntu-gnome-vgl:18.04 is having a problem
Sending the Build Context to Docker Daemon 12.29KB
Step 1/3: From ubuntu-gnome-vgl:18.04 Step 1/3: From ubuntu-gnome-vgl:18.04
pull access denied for ubuntu-gnome-vgl, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by yanbx** [comment]
I have checked the basic image query of our side and could not find Ubuntu-gnome-vgl. Can I change this basic image to Ubuntu :18.04

**Comment by yanbx** [comment]
I searched Docker Search Ubuntu-Gnome-VGL and found no result to indicate that there is no basic image. Can I use Ubuntu :18.04 or Forsrc/Ubuntu-Gnome-Desktop

**Comment by fadams** [comment]
So again I think you are misunderstanding things.

To be clear, and as I said the other day "This is the code repository for a book providing a detailed step-by-step guide to packaging and running GUI applications as Docker containers." what I mean by that is that the book is intended to provide the bulk of the documentation for the repo.

Where you are mainly going wrong is making the assumption that *everything* is a self-contained example. Now to be fair it's largely the case that things are self-contained and when you previously used the xserver-xspice-eyeos example if you'd looked at that directory carefully you would have seen that there are Dockerfiles that use xserver-xspice as a base image and others marked Dockerfile-standlone and variations on that.

The one with xserver-xspice as a base image builds upon the earlier xserver-xspice example that was described in chapter 6 of the book.

I mention that because you are looking at code from chapter 11 and making the assumption that the `ubuntu-gnome-vgl:18.04` base image is somethingto pull from say Dockerhub, it's not, rather you are expected to build that base image yourself and if you actually look through the repository you've find https://github.com/fadams/docker-gui/blob/master/10-3D-accelerated-virtual-desktops/ubuntu-18.04-gnome/Dockerfile which in turn extends the `ubuntu-gnome:18.04` image from https://github.com/fadams/docker-gui/blob/master/9-virtual-desktops/ubuntu-18.04-gnome/Dockerfile so you need to start with that one, then add 3D acceleration with VirtualGL then finally add the Remoting/HTML5 stuff.

TBH even without getting the accompanying book I think you'd get an awful lot more out of this repository (and learn a lot more) by starting from the 4-local-applications directory and working up from that rather than starting off on the more advanced topics. As it happens there is quite a lot going on in the virtual desktops.

**Comment by fadams** [comment]
Update - I've literally just built those three images and tried them out and they are all working.
